from datetime import datetime, timezone
from sqlalchemy import Column, Integer, String, Float, Text, DateTime, ForeignKey
from sqlalchemy.orm import relationship
from app.core.database import Base


class Recommendation(Base):
    """
    Financial recommendation generated by rules and LLM insights.
    Requires human-in-the-loop approval before action is recorded.
    """
    __tablename__ = "recommendations"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    title = Column(String(255), nullable=False)
    description = Column(Text, nullable=False)
    category = Column(String(100), nullable=False)  # recurring_spike, high_spend, liquidity_buffer, goal_gap
    severity = Column(String(50), default="medium", nullable=False)  # info, low, medium, high, critical
    estimated_monthly_savings = Column(Float, default=0.0, nullable=False)
    
    # AI / LLM reasoning summary
    ai_explanation = Column(Text, nullable=True)

    # Human-Approval State Machine:
    # PENDING -> APPROVED | DISMISSED | ACTED_ON
    status = Column(String(50), default="PENDING", nullable=False, index=True)
    user_notes = Column(Text, nullable=True)

    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)
    updated_at = Column(
        DateTime,
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
        nullable=False
    )

    # Relationships
    user = relationship("User", back_populates="recommendations")
    audit_logs = relationship("AuditLog", back_populates="recommendation", cascade="all, delete-orphan")
